 const Comments = [
  {
    id: 1,
    img: "https://i.pravatar.cc/50?img=1",
    nameHandler: "@johnsmith",
    comment: "This tutorial is amazing! I finally understood React Router. Thank you so much!",
    like: "2.4K",
    commentTime: "2 days ago",
  },
  {
    id: 2,
    img: "https://i.pravatar.cc/50?img=2",
    nameHandler: "@sarah_dev",
    comment: "Can you please make a video on authentication with MERN Stack?",
    like: "987",
    commentTime: "1 day ago",
  },
  {
    id: 3,
    img: "https://i.pravatar.cc/50?img=3",
    nameHandler: "@codewithalex",
    comment: "One of the best explanations I've seen on YouTube. Keep up the great work!",
    like: "1.8K",
    commentTime: "5 days ago",
  },
  {
    id: 4,
    img: "https://i.pravatar.cc/50?img=4",
    nameHandler: "@frontendmaster",
    comment: "The animations and UI are really clean. Learned a lot from this project.",
    like: "543",
    commentTime: "3 weeks ago",
  },
  {
    id: 5,
    img: "https://i.pravatar.cc/50?img=5",
    nameHandler: "@ali_codes",
    comment: "Who's watching this in 2026? 😄",
    like: "3.1K",
    commentTime: "6 months ago",
  },
  {
    id: 6,
    img: "https://i.pravatar.cc/50?img=6",
    nameHandler: "@reactlearner",
    comment: "I was stuck for hours, but this video solved my problem in just 10 minutes.",
    like: "764",
    commentTime: "4 days ago",
  },
  {
    id: 7,
    img: "https://i.pravatar.cc/50?img=7",
    nameHandler: "@codinglife",
    comment: "Excellent explanation. Looking forward to the next tutorial!",
    like: "429",
    commentTime: "1 week ago",
  },
  {
    id: 8,
    img: "https://i.pravatar.cc/50?img=8",
    nameHandler: "@techworld",
    comment: "Your teaching style is so simple and beginner-friendly. Thanks!",
    like: "1.1K",
    commentTime: "8 hours ago",
  },
  {
    id: 9,
    img: "https://i.pravatar.cc/50?img=9",
    nameHandler: "@maria_dev",
    comment: "Can you upload the source code on GitHub? It would help a lot.",
    like: "358",
    commentTime: "12 hours ago",
  },
  {
    id: 10,
    img: "https://i.pravatar.cc/50?img=10",
    nameHandler: "@devpro",
    comment: "Subscribed! This is exactly the type of content I've been looking for.",
    like: "2K",
    commentTime: "3 days ago",
  },
];

export default Comments